// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIefiaL9w0g4Zc4gTYOApXDePhH3KBUk4',
    appId: '1:461913799346:web:26686a7963d0689082a7ab',
    messagingSenderId: '461913799346',
    projectId: 'spaceylonmobile',
    authDomain: 'spaceylonmobile.firebaseapp.com',
    storageBucket: 'spaceylonmobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqmO8AaDnY9vGSeZUxJwTxo7zy-6BcAWQ',
    appId: '1:461913799346:android:dcb58cfd6d98048f82a7ab',
    messagingSenderId: '461913799346',
    projectId: 'spaceylonmobile',
    storageBucket: 'spaceylonmobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwP_UmQse0-58A9RdhB6q2P610r6vrz84',
    appId: '1:461913799346:ios:00765a05e8bf141d82a7ab',
    messagingSenderId: '461913799346',
    projectId: 'spaceylonmobile',
    storageBucket: 'spaceylonmobile.firebasestorage.app',
    iosBundleId: 'com.example.spaCeylonMobile',
  );
}
